library(lubridate)
source('ETL/extract.R')
df$CRASHLOCATION<-substr(df$CRASHLOCATION, 6, length(df$CRASHLOCATION))
df$CRASHSEVERITY<-substr(df$UNITTYPE, 6, length(df$CRASHSEVERITY))
df$GENDER<-substr(df$GENDER, 5, length(df$GENDER))
df$INJURIES<-substr(df$INJURIES, 5, length(df$INJURIES))
df$LIGHTCONDITIONSPRIMARY<-substr(df$LIGHTCONDITIONSPRIMARY, 5, length(df$LIGHTCONDITIONSPRIMARY))
df$MANNEROFCRASH<-substr(df$MANNEROFCRASH, 5, length(df$MANNEROFCRASH))
df$ROADCONDITIONSPRIMARY<-substr(df$ROADCONDITIONSPRIMARY, 6, length(df$ROADCONDITIONSPRIMARY))
df$ROADCONTOUR<-substr(df$ROADCONTOUR, 5, length(df$ROADCONTOUR))
df$ROADSURFACE<-substr(df$ROADSURFACE, 5, length(df$ROADSURFACE))
df$TYPEOFPERSON<-substr(df$TYPEOFPERSON, 5, length(df$TYPEOFPERSON))
df$WEATHER<-substr(df$WEATHER, 5, length(df$WEATHER))
df$UNITTYPE<-substr(df$UNITTYPE, 6, length(df$UNITTYPE))
df$ZIP<-strtoi(df$ZIP)
df$ZIP<-replace(df$ZIP, df$col %in% c('N45219','V45205','B45211'), substr(df$ZIP, 2, length(df$ZIP))) 
df$ZIP<-replace(df$ZIP, nchar(df$ZIP)<5, '0') 
df$CRASHDATE<-as.POSIXlt(df$CRASHDATE,format='%m/%d/%Y %H:%M:%S')
df$CRASHDATE<-ymd_hms(df$CRASHDATE)
df$DATECRASHREPORTED<-as.POSIXlt(df$DATECRASHREPORTED,format='%m/%d/%Y %H:%M:%S')
df$DATECRASHREPORTED<-ymd_hms(df$DATECRASHREPORTED)
df<-subset(df, select=-c(X)) #drop X column